# Generated by Django 4.2.3 on 2023-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_adress',
            field=models.CharField(max_length=20, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, null=True, verbose_name='사람이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='ID(이메일)'),
        ),
    ]
