# Generated by Django 4.2.3 on 2023-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_adress_user_user_name_user_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
