# Generated by Django 4.2.3 on 2023-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_adress_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_adress',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phonenum',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='전화번호'),
        ),
    ]
