# Generated by Django 4.2.3 on 2023-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_adress_user_user_name_user_user_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=0, verbose_name='회원종류'),
        ),
    ]
